Issue 122
XaoGao/rubywork_ru pull request #125
Opened 2023-12-10 18:34 UTC by sk8higher

Maybe generate kaminari config to set default values?

2023-12-13 12:32 UTC, XaoGao requested changes
@sk8higher  оставил замечания

2023-12-13 12:32 UTC, XaoGao commented on app/helpers/resume_helper.rb
> +    User.find(resume.user_id).name
@sk8higher  У резюме явная связь, разве нельзя просто resume.user.name ? так же избегай в наименовании метода get,set

2023-12-13 12:32 UTC, XaoGao commented on app/views/resumes/_resume.html.slim
> +        = link_to get_user_name(resume), resume_path(resume)
Думаю в тайтл указать ФИО и будет отдельная кнопка "показать резюме"

2023-12-13 12:32 UTC, XaoGao commented on app/views/resumes/index.html.slim
> +  - @resumes.each do |resume|
нужно перепроверить, но вроде достаточно указать =render @resumes

2023-12-13 12:32 UTC, XaoGao commented on app/views/resumes/index.html.slim
> +.container
это отдельный паршл

2023-12-13 13:20 UTC, sk8higher commented on app/helpers/resume_helper.rb
> +    User.find(resume.user_id).name
хелпер оставить и поменять или удалить?

2023-12-14 13:00 UTC, sk8higher commented
@XaoGao поправила по идее

2023-12-15 07:36 UTC, XaoGao commented
@sk8higher не вижу изменении, ты точно пушил ветку ?

2023-12-15 07:50 UTC, XaoGao requested changes
@sk8higher еще чуть-чуть подправить

2023-12-15 07:50 UTC, XaoGao commented on app/views/resumes/_resume.html.slim
> +      = link_to "Show resume", resume_path(resume), class: "btn btn-primary"
Нужна пустая строка в конце файла

2023-12-15 07:50 UTC, XaoGao commented on app/helpers/resume_helper.rb
> +module ResumeHelper
Ну теперь можно посмотреть как все это выглядит, что бы вызывать resume.user.name мы создаем модуль с одним методом который ни делает ничего кроме как выводит имя, которое скорей всего мы нигде не сможем больше использовать show_user_name(resume), давай просто удалим этот модуль, а в коде пока будем вызывать resume.user.name

2023-12-15 07:50 UTC, XaoGao commented on app/views/resumes/index.html.slim
> +.container
@sk8higher надо вынести 
.container
  .row
    .col.text-center.d-flex.justify-content-center.mt-3
      = paginate @resumes
      
В отдельный файл, а @resume передавать как параметр, так как в будущем у нас будут пагинации и для других объектов

2023-12-15 07:55 UTC, sk8higher commented on app/views/resumes/index.html.slim
> +.container
вынести в shared/_pagination?

2023-12-17 11:13 UTC, XaoGao reviewed
@sk8higher тегни когда внисешь изменения

2023-12-17 11:13 UTC, XaoGao commented on app/views/resumes/index.html.slim
> +.container
@sk8higher давай

2023-12-18 06:02 UTC, sk8higher commented
@XaoGao пофиксила

2023-12-20 11:48 UTC, XaoGao approved these changes

2023-12-20 11:48 UTC, merged