added Reaction model
XaoGao/rubywork_ru pull request #126
Opened 2023-12-14 21:04 UTC by Tavbulatov

2023-12-15 07:43 UTC, XaoGao requested changes
@Tavbulatov оставил замечания

2023-12-15 07:43 UTC, XaoGao commented on app/models/reaction.rb
> +class Reaction < ApplicationRecord
@Tavbulatov добавь тут belongs_to, а в связанных моделях has_many

2023-12-15 07:43 UTC, XaoGao commented on spec/factories/reactions.rb
> +FactoryBot.define do
надо снова запустить гем annotate чтобы тут тоже был комментарии полей модели

2023-12-15 07:43 UTC, XaoGao commented on spec/factories/reactions.rb
> +    user { nil }
удалить { nil }

2023-12-15 07:43 UTC, XaoGao commented on spec/factories/reactions.rb
> +    vacancies { nil }
тоже удалить nil

2023-12-15 07:43 UTC, XaoGao commented on spec/factories/reactions.rb
> +    cover_letter { "MyText" }
Лучше генерировать через Faker можно посмотреть другие factories

2023-12-15 07:43 UTC, XaoGao commented on app/models/reaction.rb
> +class Reaction < ApplicationRecord
Тут так же стоит добавить валидацию для cover_letter

2023-12-16 11:34 UTC, Tavbulatov commented
@XaoGao Сheck

2023-12-17 11:11 UTC, XaoGao approved these changes
@Tavbulatov ставлю approve, но ты когда вызвал гем ammotation изменил описание и других моделей, вроде в этом геме можно указать какие модели описать, ну или хотя бы не нужно было коммитить изменения, которые не относятся к задаче

2023-12-17 11:12 UTC, merged