PlaceOfWork Model is created
XaoGao/rubywork_ru pull request #89
Opened 2023-09-26 16:07 UTC by zarina86

Complete, check PR

2023-09-27 07:28 UTC, XaoGao requested changes
@zarina86 fix pls

2023-09-27 07:28 UTC, XaoGao commented on db/migrate/20230926152729_create_place_of_works.rb
> +      t.datetime :Start, null: false
@zarina86 use lower case

2023-09-27 07:28 UTC, XaoGao commented on db/migrate/20230926152729_create_place_of_works.rb
> +      t.datetime :End, null: true
@zarina86 use lower case

2023-09-30 05:05 UTC, zarina86 commented on db/migrate/20230926152729_create_place_of_works.rb
> +      t.datetime :Start, null: false
Requested changes are comleted

2023-09-30 05:05 UTC, zarina86 commented on db/migrate/20230926152729_create_place_of_works.rb
> +      t.datetime :End, null: true
Done

2023-09-30 08:52 UTC, merged